remote_theme             : "mmistakes/minimal-mistakes@4.24.0"

minimal_mistakes_skin    : "dark"

# Site Settings
locale                   : "en-US"
title                    : "MBagrat"
title_separator          : "-"
subtitle                 : "Yet another developer's blog."
name                     : &name "Bagrat Mukaelyan"
description              : &description "“Adapt what is useful, reject what is useless, and add what is specifically your own.” - *Bruce Lee*"
url                      : https://mbagrat.github.io
baseurl                  : ""
repository               : "MBagrat/mbagrat.github.io"
teaser                   : "/assets/images/500x300.png"
logo                     : "assets/images/120x88.png"
masthead_title           : "MBagrat"
breadcrumbs              : true


comments:
  provider               : "disqus"
  disqus:
    shortname            : mbagrat


reCaptcha:
  siteKey                : 6Lc5JoYeAAAAAH8uTmIJOxk5PSgUgJFTNFmMe5ay
  secret                 : 6Lc5JoYeAAAAAKe02KqBeqzpZt19GdcQwGFgC5NL


atom_feed:
  path                   : # blank (default) uses feed.xml

search                   : true
search_full_content      : true
search_provider          : lunr


# SEO Related
google_site_verification : "4VtGdguzZe-wl5BbJiuRB88k3wUyEKIpNz4AX4eJFU8" # Replace this with your ID, or delete
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               : &twitter "mukaelyanbagrat"
facebook:
  username               : &facebook "mbagrat"
  app_id                 :
  publisher              :
og_image                 : "/assets/images/site-logo.png" # Open Graph/Twitter default site image
# For specifying social profiles, used in _includes/seo.html
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : Person # Person or Organization (defaults to Person)
  name                   : *name # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://twitter.com/mukaelyanbagrat"
    - "https://www.facebook.com/mbagrat"

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "UA-2011187-3" # Replace this with your ID, or delete
    anonymize_ip         : true


# Site Author
author:
  name             : *name # *name is a YAML reference pointing to the &anchor earlier
  avatar           : "/assets/images/bagrat-mukaelyan.jpeg"
  bio              : *description #"Just another *boring*, *tattooed*, *time traveling*, *designer*."
  location         : "Yerevan, Armenia"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:bagrat.mukaelyan@gmail.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.mbagrat.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bagratmukaelyan/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mukaelyanbagrat"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/mbagrat"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MBagrat"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/bagrat_mukaelyan/"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:


# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
      start_line: 1


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      show_date: true
      author_profile: true
      comments: true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/New_York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path>/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path>/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
